// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuqkRI1qLsenkD_0U6nngnkYy5_5HK8M0',
    appId: '1:256967708793:web:db0095ffd365aef98804a8',
    messagingSenderId: '256967708793',
    projectId: 'projetintegrateurv2',
    authDomain: 'projetintegrateurv2.firebaseapp.com',
    storageBucket: 'projetintegrateurv2.appspot.com',
    measurementId: 'G-QTC1G2ZX3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwJdfJ0KtJrG5-_HVSYXoCYWQUa-yZeEs',
    appId: '1:256967708793:android:17c5e7575c1f5adc8804a8',
    messagingSenderId: '256967708793',
    projectId: 'projetintegrateurv2',
    storageBucket: 'projetintegrateurv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkPEARCaA39HyU_PJV5-PZt0D57v_hpkk',
    appId: '1:256967708793:ios:dccd072750da83378804a8',
    messagingSenderId: '256967708793',
    projectId: 'projetintegrateurv2',
    storageBucket: 'projetintegrateurv2.appspot.com',
    iosClientId: '256967708793-0fth3rbpruo2a6u05vu0rk8a7qvcqj74.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetCdn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkPEARCaA39HyU_PJV5-PZt0D57v_hpkk',
    appId: '1:256967708793:ios:dccd072750da83378804a8',
    messagingSenderId: '256967708793',
    projectId: 'projetintegrateurv2',
    storageBucket: 'projetintegrateurv2.appspot.com',
    iosClientId: '256967708793-0fth3rbpruo2a6u05vu0rk8a7qvcqj74.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetCdn',
  );
}
