// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS7vaCX9Bs7rxLRZ_pQBqnhR0_5DYWmH8',
    appId: '1:360560152045:web:08ef813579e1dc28422be4',
    messagingSenderId: '360560152045',
    projectId: 'projet-integrateur-37b6f',
    authDomain: 'projet-integrateur-37b6f.firebaseapp.com',
    storageBucket: 'projet-integrateur-37b6f.appspot.com',
    measurementId: 'G-YEGN22T02W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrBIT6wKN4RBlx9d5YZ7u9Md0aVJMgBXc',
    appId: '1:360560152045:android:dc053b681a405945422be4',
    messagingSenderId: '360560152045',
    projectId: 'projet-integrateur-37b6f',
    storageBucket: 'projet-integrateur-37b6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArAIac6sVETKN6zzlNrswnTpzHpyAOKbU',
    appId: '1:360560152045:ios:af43c32ded853a67422be4',
    messagingSenderId: '360560152045',
    projectId: 'projet-integrateur-37b6f',
    storageBucket: 'projet-integrateur-37b6f.appspot.com',
    iosClientId: '360560152045-ccg4aucfdvm67g5mdd0tl5hd1agm97c8.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetCdn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArAIac6sVETKN6zzlNrswnTpzHpyAOKbU',
    appId: '1:360560152045:ios:af43c32ded853a67422be4',
    messagingSenderId: '360560152045',
    projectId: 'projet-integrateur-37b6f',
    storageBucket: 'projet-integrateur-37b6f.appspot.com',
    iosClientId: '360560152045-ccg4aucfdvm67g5mdd0tl5hd1agm97c8.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetCdn',
  );
}
