// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoVcTFWGMWg4WXou9z45oANtJ8VyXcLIE',
    appId: '1:688345228456:web:7c5f234236c2be80644e9d',
    messagingSenderId: '688345228456',
    projectId: 'integrateurcdn',
    authDomain: 'integrateurcdn.firebaseapp.com',
    storageBucket: 'integrateurcdn.appspot.com',
    measurementId: 'G-L7ENW3BJSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOQveGR1a5sEbqqlDXHTNcXsXCFqH0IbY',
    appId: '1:688345228456:android:ea754697be71adc4644e9d',
    messagingSenderId: '688345228456',
    projectId: 'integrateurcdn',
    storageBucket: 'integrateurcdn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE-laZQrW0dWJL4VvBU6D101qdDDRw59Y',
    appId: '1:688345228456:ios:2beff3ed01157606644e9d',
    messagingSenderId: '688345228456',
    projectId: 'integrateurcdn',
    storageBucket: 'integrateurcdn.appspot.com',
    iosClientId: '688345228456-mjdbeukad4p3bb0fji47kf1o5ntpeqtb.apps.googleusercontent.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE-laZQrW0dWJL4VvBU6D101qdDDRw59Y',
    appId: '1:688345228456:ios:2beff3ed01157606644e9d',
    messagingSenderId: '688345228456',
    projectId: 'integrateurcdn',
    storageBucket: 'integrateurcdn.appspot.com',
    iosClientId: '688345228456-mjdbeukad4p3bb0fji47kf1o5ntpeqtb.apps.googleusercontent.com',
    iosBundleId: 'com.example.test1',
  );
}
